### ISSUE TITLE
求告知热部署和冷部署的区别的资料

### ISSUE THREAD

**Issue by appleyuchi** [kingname/SourceCodeofMongoRedis#12]
**作者大大:
您好！**
13.3.1 “多Redis实例”与“单Redis实例多数据库”的差异
中提到了热部署和冷部署．

①请问热部署和冷部署的区别是什么?

②＂新版本又涉及 Redis 键值的修改＂,新版本的redis不能直接连接旧版本的redis库吗？这个修改是redis升级导致的自动修改吗?

如果不方便阐述，有相关资料亦可，自己有事先百度过，但是没找到匹配的资料，
感谢

**Comment by kingname** [comment]
## 冷热部署的区别

我在书上，说的冷部署的意思是，你需要把所有使用这个 Redis 的程序全部停了，然后更新代码，再同时启动。热部署就是，可以一部分程序使用老代码，另一部分程序使用新的代码。

> 新版本又涉及 Redis 键值的修改

我在书上的意思是说，你新的代码会修改这个 Key，例如原来是列表，现在要改成集合了。但是老的程序还在运行，如果不提前把所有老程序都停了，那么新部署的程序改了这个 Key 以后，老程序就会报错。
