### ISSUE TITLE
chapter_4

### ISSUE THREAD

**Issue by lzySingularity** [kingname/SourceCodeofMongoRedis#5]
I got werkzeug TypeError when I run code in  chapter_4.
![image](https://user-images.githubusercontent.com/41995075/74633740-48201980-519d-11ea-85f7-808695883341.png)
These are the versions of my python packages.

**Comment by kingname** [comment]
麻烦提供一下具体报错信息截图。werkzeug 不用单独安装，你安装 Flask 的时候，它自动就会安装了。

**Comment by kingname** [comment]
Please provide the screenshot of the error. And you should not install werkzeug manually. when you install Flask, it will be installed automatically.

**Comment by kingname** [comment]
not enough info to solve the problem.
