### ISSUE TITLE
第12章希望顯示自帶數據集

### ISSUE THREAD

**Issue by appleyuchi** [kingname/SourceCodeofMongoRedis#7]
作者大大:
您好！
目前代碼一切正常，
有些小缺憾:
doc_to_redis.py這個文件夾是用來讓書中自帶數據集生效的，
裏面有兩個for循環，
第1個用來在redis中導入“自帶問題集”
第2個用來在redis中導入“自帶答案集”
目前已經修復了第一個，希望作者修復第2個for循環，感謝~！
修復第一個for循環後的代碼是:
https://paste.ubuntu.com/p/7bBwFxq3jY/

总共包含三个问题:
自带数据集-question在页面不显示
自带数据集-answer在页面不显示
自带数据集-vote在页面显示数据与mongodb中记录的不同.

**Comment by kingname** [comment]
收到。

**Comment by kingname** [comment]
正如你所说，没有显示问题和答案，原因在于后端是通过查询 Redis 中的 qa_system:question:vote 和 qa_system:answer:{question_id}:vote 来获取将会显示的问题或者回答列表。但是如果这几个 Key 是空的，确实就什么都不会显示。

**Comment by kingname** [comment]
12章问题已经修复。
