### ISSUE TITLE
问答系统可以反复点赞

### ISSUE THREAD

**Issue by appleyuchi** [kingname/SourceCodeofMongoRedis#9]
您好
似乎是少了逻辑约束，
同一个用户可以对同一个问题反复点赞．

**Comment by kingname** [comment]
是的，这个地方是故意这样设计的，当你想对一个问题或者回答表示强烈赞赏的时候，你可以连续点很多赞，把它顶上去。（当然，这回导致刷赞的行为）。12章不会进行限制。在第13章的优化里面再来做限制。
